### ISSUE TITLE
Limpieza y renombrado del directorio `images`

### ISSUE THREAD

**Issue by lauramcastro** [ivangonzalezcotelo/practicaVVS#4]
La nomenclatura y contenido de este directorio es curiosa. A priori, parecería que sus contenidos pertenecen al ámbito de la documentación (diagramas), por lo que su nomenclatura más adecuada sería `doc`.

Por otro lado, hay en él ficheros de formato no estándar ni libre (por ejemplo, `DiseñoER.vsdx`, `PA- AuctionHouse.mdzip`), que deberían eliminarse, sobre todo estando presentes sus versiones en formatos sí interoperables (`DiseñoER.png`).

Por último, la presencia de los ficheros de texto `TO DO WEB` y `TO DO.txt` está claramente fuera de lugar.

**Comment by balvarezg** [comment]
Eliminados los diagramas de formato no estándar y los ficheros `TO DO WEB` y `TO DO.txt`.
El resto de diagramas están ahora alojados en la carpeta (`diagrams`) dentro de (`doc`).
